### ISSUE TITLE
document scope tagging

### ISSUE THREAD

**Issue by alex-pavlides-adarga** [jkkummerfeld/annotation-terminal-tool#4]
Hi,

This is a great project, perfect for what we need, however we ran into an issue that is preventing us from using it. Our use case is to add a binary tag to whole documents. I followed your documentation and first created a data-list like: 

`find . -name "*.txt" > filenames_todo`

I then ran:

`slate -d filenames_todo -t categorical -s document -l do_later`

which returns the error: File "/usr/local/lib/python3.7/site-packages/slate/view.py", line 18, in __init__ . self.top = max(0, cursor.start[0] - self.window.getmaxyx()[0] - 10)
IndexError: tuple index out of range

It works as expected when -s is token, line etc, so it is specific to document.

**Comment by jkkummerfeld** [comment]
Thanks for raising this. I'm looking into it now.

**Comment by jkkummerfeld** [comment]
I've pushed a fix that I think resolves this (a7b72db2ffaf0df8729b020c530af666b07878ea). I'll close this issue for now, but please re-open it if that didn't do the trick!

**Comment by jkkummerfeld** [comment]
Changed my mind - I'll leave this open until you let me know it's working for you.

Until then, the changes are only here on github (not on pip).

**Comment by alex-pavlides-adarga** [comment]
That's fixed it, you can close this issue. Thanks for the fast turn around! I may have another issue, but I am not sure if its me this time. If it is i'll open another issue.

**Comment by jkkummerfeld** [comment]
Even if the next issue turns out to be solvable, it may indicate that the documentation needs some improvement :) So let me know if it's a non-obvious solution!
