### ISSUE TITLE
resuming tagging

### ISSUE THREAD

**Issue by alex-pavlides-adarga** [jkkummerfeld/annotation-terminal-tool#5]
I successfully completed a round of tagging but took a break and then tried to resume from where I left off. To do this I followed your documentation, along the line of:
`./slate.py -d do_later.todo -l do_even_later` by using:
`python ../slate-master/slate.py -d do_later.todo -t categorical -s document -l do_even_later`
This raises an exception: 
File "/Users/alex/Documents/Projects/doc_clustering/bbc/slate-master/slate/data.py", line 70, in process_fileinfo
    raise Exception(error)
Exception: Input Filename List Has Errors

When I had a look at this file it is formatted differently to the original data-list. It looks like:
./289.txt ./289.txt.annotations ((), ()) 
./504.txt ./504.txt.annotations ((), ()) 
./262.txt ./262.txt.annotations ((), ()) 

That may or may not be the issue, I'm not sure. 

The other thing it complains about is that output files already exist, i.e. 

Output file already exists:
./289.txt.annotations
./504.txt.annotations
./262.txt.annotations
./276.txt.annotations

My gut feeling is that there should only be a single annotations file, and also that if I'm resuming a session that it shouldn't complain about files that already exist. 

Looking forward for clarification. Thanks!

**Comment by jkkummerfeld** [comment]
1. Exception: Input Filename List Has Errors - This is a bug. Looking into it now.
2. Output file already exists - This can be ignored by using the `-o` command line argument, which will then overwrite annotations. The system actually has no notion of a 'session', you could create your own todo file (with the right format) and start from there the first time (which is what I did when managing a set of annotators on one project).
3. Multiple annotation files - I can see the argument for a single file, particularly in the document tagging case. It would involve a little work to add as an option though. Ultimately it's a design decision that went the other way at some early stage :)

**Comment by jkkummerfeld** [comment]
Ah, realised you had broken up the error message, I am guessing it was actually:

```
File "/Users/alex/Documents/Projects/doc_clustering/bbc/slate-master/slate/data.py", line 70, in process_fileinfo
raise Exception(error)
Exception: Input Filename List Has Errors

Output file already exists:
./289.txt.annotations
./504.txt.annotations
./262.txt.annotations
./276.txt.annotations
```

Those are intended to be a single error. I'm going to adjust the error message to be clearer.

**Comment by jkkummerfeld** [comment]
Pushed a fix to the error message and documentation that should clarify this (a89c00c)
